imports:
  - php

filter:
  excluded_paths: [vendor/*, test/*]

build:
  project_setup:
    before:
      - mkdir -p /home/scrutinizer/build/config/cache/anax
      - chmod -R 777 /home/scrutinizer/build/config/cache/anax
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    tests-and-coverage:
      tests:
        override:
          -
            command: "make phpunit"
            coverage:
              file: "build/coverage.clover"
              format: "php-clover"

