imports:
  - php

filter:
  excluded_paths: [vendor/*, test/*]

build:

    dependencies:
      before:
        -
          command: "mkdir build"
          "- chmod -R 777 /home/travis/build/AsaTirsen/weather/cache/anax


    tests:
        override:
          -
            command: "make phpunit"
            coverage:
              file: "build/coverage.clover"
              format: "php-clover"

