imports:
  - php

filter:
  excluded_paths: [vendor/*, test/*]

build:

    dependencies:
      before:
        - "mkdir -p /home/scrutinizer/build/cache/anax"
    environment:
      variables:
        LOCATIONAPIKEY: "52ca019cf35f1e86f782ed09916211c8"
        WEATHERAPIKEY: "c7a66a573b79dd6c14f14a2e93ed0d11"
    tests:
      before:
        - "chmod -R 777 /home/scrutinizer/build/cache/anax"
      override:
        -
          command: "make phpunit"
          coverage:
            file: "build/coverage.clover"
            format: "php-clover"
